# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # v5
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: master
    labels:
      - "dependencies"
      - "pip"

  # Dependabot Updates are temporary disabled - 2025/03/19
  # - package-ecosystem: "pip"
  #   directory: "/api"
  #   schedule:
  #     interval: "daily"
  #   open-pull-requests-limit: 10
  #   target-branch: master
  #   labels:
  #     - "dependencies"
  #     - "pip"
  #     - "component/api"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: master
    labels:
      - "dependencies"
      - "github_actions"

  # Dependabot Updates are temporary disabled - 2025/03/19
  # - package-ecosystem: "npm"
  #   directory: "/ui"
  #   schedule:
  #     interval: "daily"
  #   open-pull-requests-limit: 10
  #   target-branch: master
  #   labels:
  #     - "dependencies"
  #     - "npm"
  #     - "component/ui"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: master
    labels:
      - "dependencies"
      - "docker"

  # v4.6
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: v4.6
    labels:
      - "dependencies"
      - "pip"
      - "v4"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: v4.6
    labels:
      - "dependencies"
      - "github_actions"
      - "v4"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: v4.6
    labels:
      - "dependencies"
      - "docker"
      - "v4"

  # v3
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    target-branch: v3
    labels:
      - "dependencies"
      - "pip"
      - "v3"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    target-branch: v3
    labels:
      - "dependencies"
      - "github_actions"
      - "v3"
