### Account, Check and/or Region can be * to apply for all the cases.
### Account == <Cloudflare Account ID>
### Region == <Cloudflare Zone ID> (use * for all zones)
### Resources and tags are lists that can have either Regex or Keywords.
### Tags is an optional list that matches on tuples of 'key=value' and are "ANDed" together.
### Use an alternation Regex to match one of multiple tags with "ORed" logic.
### For each check you can except Accounts, Regions, Resources and/or Tags.
###########################  MUTELIST EXAMPLE  ###########################
Mutelist:
  Accounts:
    "example-account-id":
      Checks:
        "zone_dnssec_enabled":
          Regions:
            - "*"
          Resources:
            - "example-zone-id"
            - "another-zone-id"
