### Account, Check and/or Region can be * to apply for all the cases.
### Account == M365 Tenant and Region == M365 Location
### Resources and tags are lists that can have either Regex or Keywords.
### Tags is an optional list that matches on tuples of 'key=value' and are "ANDed" together.
### Use an alternation Regex to match one of multiple tags with "ORed" logic.
### For each check you can except Accounts, Regions, Resources and/or Tags.
###########################  MUTELIST EXAMPLE  ###########################
Mutelist:
  Accounts:
    "*":
      Checks:
        "admincenter_groups_not_public_visibility":
          Regions:
            - "westeurope"
          Resources:
            - "sqlserver1"           # Will ignore sqlserver1 in check sqlserver_tde_encryption_enabled located in westeurope
          Description: "Findings related with the check sqlserver_tde_encryption_enabled is muted for westeurope region and sqlserver1 resource"
        "defender_*":
          Regions:
            - "*"
          Resources:
            - "*"                 # Will ignore every Defender check in every location
        "*":
          Regions:
            - "*"
          Resources:
            - "test"
          Tags:
            - "test=test"         # Will ignore every resource containing the string "test" and the tags 'test=test' and
            - "project=test|project=stage" # either of ('project=test' OR project=stage) in Azure subscription 1 and every location

    "*":
      Checks:
        "admincenter_*":
          Regions:
            - "*"
          Resources:
            - "*"
          Exceptions:
            Accounts:
              - "Tenant1"
            Regions:
              - "eastus"
              - "eastus2"        # Will ignore every resource in admincenter checks except the ones in Tenant1 located in eastus or eastus2
