### Account, Check and/or Region can be * to apply for all the cases.
### Account == MongoDB Atlas Project ID and Region == MongoDB Atlas Cluster Region
### Resources and tags are lists that can have either Regex or Keywords.
### Tags is an optional list that matches on tuples of 'key=value' and are "ANDed" together.
### Use an alternation Regex to match one of multiple tags with "ORed" logic.
### For each check you can except Accounts, Regions, Resources and/or Tags.
###########################  MONGODB ATLAS MUTELIST EXAMPLE  ###########################
Mutelist:
  Accounts:
    "your-project-id-here":
      Checks:
        "clusters_authentication_enabled":
          Regions:
            - "US_EAST_1"
          Resources:
            - "test-cluster"
          Description: "Mute clusters_authentication_enabled check for test-cluster in US_EAST_1 region"
        "projects_auditing_enabled":
          Regions:
            - "*"
          Resources:
            - "*"
          Description: "Mute projects_auditing_enabled check for all resources in all regions"

    "*":
      Checks:
        "clusters_backup_enabled":
          Regions:
            - "WESTERN_EUROPE"
          Resources:
            - "*"
          Description: "Mute clusters_backup_enabled check for all clusters in all regions"
