### Project, Check and/or Region can be * to apply for all the cases.
### Project == <StackIT Project ID>
### Resources and tags are lists that can have either Regex or Keywords.
### Tags is an optional list that matches on tuples of 'key=value' and are "ANDed" together.
### Use an alternation Regex to match one of multiple tags with "ORed" logic.
### For each check you can except Projects, Regions, Resources and/or Tags.
###########################  MUTELIST EXAMPLE  ###########################
Mutelist:
  Accounts:
    "project_id_1":
      Checks:
        "objectstorage_bucket_encryption":
          Regions:
            - "*"
          Resources:
            - "bucket_name_1"
            - "bucket_name_2"
          Tags:
            - "environment=dev"
    "project_id_2":
      Checks:
        "*":
          Regions:
            - "eu01"
          Resources:
            - ".*-test$"
