apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prowler.fullname" . }}-ui
  labels:
    {{- include "prowler.labels" . | nindent 4 }}
spec:
  {{- if not .Values.ui.autoscaling.enabled }}
  replicas: {{ .Values.ui.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "prowler.fullname" . }}-ui
  template:
    metadata:
      annotations:
        secret-hash: {{ .Files.Get "templates/ui/configmap.yaml" | sha256sum }}
      {{- with .Values.ui.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "prowler.labels" . | nindent 8 }}
        app.kubernetes.io/name: {{ include "prowler.fullname" . }}-ui
        {{- with .Values.ui.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.ui.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "prowler.ui.serviceAccountName" . }}
      {{- with .Values.ui.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: ui
          {{- with .Values.ui.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ui.service.port }}
              protocol: TCP
          env:
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ui.authSecret.secretKeyRef.name }}
                  key: {{ .Values.ui.authSecret.secretKeyRef.key }}
          envFrom:
            - configMapRef:
                name: {{ include "prowler.fullname" . }}-ui
            {{- with .Values.ui.secrets }}
            {{- range $index, $secret := . }}
            - secretRef:
                name: {{ $secret }}
            {{- end }}
            {{- end }}
          {{- with .Values.ui.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ui.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ui.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ui.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.ui.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
