apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prowler-api.fullname" . }}
  labels:
    {{- include "prowler-api.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | toString | b64enc | quote }}
  {{- end }}