name: 'Tools: Comment Label Update'

on:
  issue_comment:
    types:
      - 'created'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number }}
  cancel-in-progress: false

jobs:
  update-labels:
    if: contains(github.event.issue.labels.*.name, 'status/awaiting-response')
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Remove 'status/awaiting-response' label
        uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0 # v1.3.0
        with:
          labels: status/awaiting-response

      - name: Add 'status/waiting-for-revision' label
        uses: actions-ecosystem/action-add-labels@18f1af5e3544586314bbe15c0273249c770b2daf # v1.1.3
        with:
          labels: status/waiting-for-revision
